name: wabi
services:
- name: wabi-backend
  github:
    repo: AzureFoxStudios/wabi
    branch: main
  envs:
  - key: PORT
    value: "3000"
  - key: NODE_ENV
    value: production
  - key: FRONTEND_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_DOMAIN}
  - key: PUBLIC_URL
    scope: RUN_AND_BUILD_TIME
    value: ${APP_DOMAIN}
  http_port: 3000
  health_check:
    http_path: /health
